IF NOT EXISTS(SELECT TOP 1 * FROM sys.databases WHERE name = 'DB_MSERVER') 
BEGIN
	CREATE DATABASE [DB_MSERVER];
END
GO
USE [DB_MSERVER];
IF OBJECT_ID(N'dbo.TB_PRT_USER', N'U') IS NULL
BEGIN
	CREATE TABLE TB_PRT_USER (
		CL_ID NVARCHAR(15) NOT NULL PRIMARY KEY,
		CL_NAME NVARCHAR(50) NOT NULL,
		CL_CAREER NVARCHAR(30) NOT NULL,
		CL_DATETIME DATETIME NOT NULL,
		CL_DEFAULT TINYINT
	);
END
IF OBJECT_ID(N'dbo.TB_PRT_UEXPERIENCE', N'U') IS NULL
BEGIN
	CREATE TABLE TB_PRT_UEXPERIENCE (
		CL_ID NVARCHAR(15) NOT NULL PRIMARY KEY,
		CL_USER NVARCHAR(15) NOT NULL,
		CL_CAREER NVARCHAR(200) NOT NULL,
		CL_COMPANY NVARCHAR(200) NOT NULL,
		CL_START_DATETIME DATETIME NOT NULL,
		CL_STOP_DATETIME DATETIME NULL,
		CL_CURRENT TINYINT NULL
	);
END
IF OBJECT_ID(N'TB_PRT_UEX_DESCRIPTION', N'U') IS NULL
BEGIN
	CREATE TABLE TB_PRT_UEX_DESCRIPTION (
		CL_ID NVARCHAR(15) NOT NULL PRIMARY KEY,
		CL_EXPERIENCE NVARCHAR(15) NOT NULL,
		CL_DESCRIPTION NVARCHAR(MAX) NOT NULL,
		CL_DATETIME DATETIME NOT NULL
	);
END
IF OBJECT_ID(N'TB_PRT_UEX_SKILL_SVG', N'U') IS NULL
BEGIN
	CREATE TABLE TB_PRT_UEX_SKILL_SVG (
		CL_ID NVARCHAR(15) NOT NULL PRIMARY KEY,
		CL_EXPERIENCE NVARCHAR(15) NOT NULL,
		CL_SVG NVARCHAR(MAX) NOT NULL
	);
END
IF OBJECT_ID(N'TB_PRT_UEX_SKILL_SVG_FRAMWORK', N'U') IS NULL
BEGIN
	CREATE TABLE TB_PRT_UEX_SKILL_SVG_FRAMWORK (
		CL_ID NVARCHAR(15) NOT NULL PRIMARY KEY,
		CL_SVG NVARCHAR(15) NOT NULL,
		CL_FNAME NVARCHAR(30) NOT NULL,
		CL_DESCRIPTION NVARCHAR(MAX) NOT NULL
	);
END
IF OBJECT_ID(N'TB_PRT_UEDUCATION', N'U') IS NULL
BEGIN
	CREATE TABLE TB_PRT_UEDUCATION(
		CL_ID NVARCHAR(15) NOT NULL PRIMARY KEY,
		CL_USER NVARCHAR(15) NOT NULL,
		CL_DEGREE NVARCHAR(30) NOT NULL,
		CL_MAJOR NVARCHAR(200) NOT NULL,
		CL_UNIVERSITY NVARCHAR(200) NOT NULL,
		CL_FINISHED DATE NOT NULL,
		CL_GPA FLOAT NOT NULL,
		CL_RESEARCH_NAME NVARCHAR(MAX) NOT NULL,
		CL_RESEARCH_LINK NVARCHAR(MAX) NULL,
	);
END
IF OBJECT_ID(N'TB_PRT_UEDU_TABLE', N'U') IS NULL
BEGIN
	CREATE TABLE TB_PRT_UEDU_TABLE (
		CL_ID NVARCHAR(15) NOT NULL PRIMARY KEY,
		CL_EDUCATION NVARCHAR(15) NOT NULL,
		CL_COURSE NVARCHAR(MAX) NOT NULL,
		CL_CREDIT FLOAT NOT NULL,
		CL_GRADE FLOAT NOT NULL,
		CL_DATETIME DATETIME NOT NULL
	);
END
IF OBJECT_ID(N'TB_PRT_UBACKGROUND', N'U') IS NULL
BEGIN
	CREATE TABLE TB_PRT_UBACKGROUND (
		CL_ID NVARCHAR(15) NOT NULL,
		CL_USER NVARCHAR(15) NOT NULL,
		CL_PIC_LINK NVARCHAR(200) NOT NULL,
		CL_PMODE NVARCHAR(100) NOT NULL
	);
END